Repository CBNU-FinFlow/Server, pull requests merged in 2025-03, with the labels that each got.

#37 [FIX] 보유 자산/거래 내역 추가 API 수정
  Dockerfile
  app/models/__pycache__/user.cpython-312.pyc
  app/routers/assets.py
  app/schemas/asset.py
  docker-compose.yml
Labels: fix

#39 [chore] docker-compose.yml 수정
  README.md
  docker-compose.yml
Labels: chore

#41 [fix] 보유 자산 조회 API 수정
  app/routers/assets.py
Labels: fix

#45 [fix] 거래 내역 조회 API 수정
  app/crud/transaction.py
  app/routers/transaction.py
Labels: fix

#43 [fix] 보유량이 0이 될시 DB에서 삭제하도록 수정
  app/routers/assets.py
Labels: fix

#47 [feat] 보유 자산 전송 API 추가
  app/routers/assets.py
  app/routers/transaction.py
Labels: feat

#53 [fix] 거래 내역 조회 API 섹터도 반환하도록 수정
  app/routers/transaction.py
Labels: fix
